version: "3.7"
services:
  pghero:
    image: ankane/pghero
    container_name: PGHERO
    #network_mode: host
    ports:
      - "8182:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PGHERO_USERNAME=${PGHERO_USERNAME}
      - PGHERO_PASSWORD=${PGHERO_PASSWORD}
    volumes:
      - ./pghero.yml:/app/config/pghero.yml
    #command: bin/rake pghero:capture_query_stats